export type {
  CompensationAbsoluteDeduction,
  CompensationAccidentType,
  CompensationBaseInput,
  CompensationDataVersions,
  CompensationDeductionsInput,
  CompensationDeductionsResult,
  CompensationFaultOffset,
  CompensationIndustrialBenefitResult,
  CompensationIndustrialInsuranceInjury,
  CompensationInput,
  CompensationLossRateInput,
  CompensationLostIncomeInput,
  CompensationRatioDeduction,
  CompensationLegacyRatioDeduction,
  CompensationResult,
  CompensationSegment,
  Hoffman240CapTable,
  LaborRateEffectiveRule,
  CompensationWarning,
  PermanentDisabilityInput,
  TemporaryDisabilityInput,
} from "./types";
export { computeCompensation, type ComputeCompensationDeps } from "./compute";
export { validateCompensationInput } from "./validators";
