export type {
  CalcOptions,
  InterestInput,
  InterestResult,
  InterestSegment,
  IsoDate,
  LegalRateCode,
  LegalRatePreset,
  RateSegment,
} from "./types";

export type { LegalRateDataset, LegalRateRecord } from "./legal-rates";
export type { CalculateInterestDeps } from "./interest";
export type { ResolveSegmentsDeps } from "./segments";
export type { InterestLimitDataset, InterestLimitLaw, InterestLimitSlice } from "./interest-limits";

export { calculateInterest } from "./interest";
export { addDays, addYears, containsLeapDay, countDays, daysInYear, isLeapYear } from "./days";
export { resolveSegments } from "./segments";
export { datasetVersionTag, getRateAt, rateHistoryFor } from "./legal-rates";
export {
  capHistoryFor,
  getCapAt,
  interestLimitsVersionTag,
  loadInterestLimits,
} from "./interest-limits";
export { STANDARD_DISCLAIMER } from "./disclaimers";

export type {
  HeirNode,
  InheritanceInput,
  InheritanceResult,
  InheritanceShare,
} from "./inheritance";
export { calculateInheritance } from "./inheritance";

export type {
  AllocationTarget,
  AppropriationAllocationDirective,
  AppropriationAllocationType,
  AppropriationClaimInput,
  AppropriationClaimResult,
  AppropriationInput,
  AppropriationPaymentInput,
  AppropriationPaymentResult,
  AppropriationProportionalShare,
  AppropriationResult,
  AppropriationStatutoryRank,
  AppropriationTotals,
} from "./appropriation";
export {
  APPROPRIATION_DATA_VERSION,
  computeAppropriation,
  validateAppropriationInput,
} from "./appropriation";

export type {
  AppealsLevel,
  ApplyLawyerFeeDiscountsResult,
  CaseType,
  CaseTypeMeta,
  ComputeDeliveryFeeDeps,
  ComputeLitigationCostDeps,
  ComputeLawyerFeeDeps,
  ComputeStampDutyDeps,
  DeliveryCount,
  DeliveryCountMatrixEntry,
  DeliveryDataset,
  DeliveryFeeInput,
  DeliveryFeeResult,
  DeliveryFormula,
  DeliveryHistoryNote,
  DeliveryMatrixDelegation,
  DeliveryRuleChange,
  DeliverySourceLaw,
  DeliveryUnitPriceHistoryEntry,
  DeliveryUnverifiedEntry,
  Domain,
  KlacScopeWarning,
  LawyerFeeAppealsRule,
  LawyerFeeAppealsRuleMeta,
  LawyerFeeBracket,
  LawyerFeeBracketTableChange,
  LawyerFeeCourtDiscretionModifier,
  LawyerFeeCustomPercentModifier,
  LawyerFeeDataset,
  LawyerFeeDiscount,
  LawyerFeeHistoryNote,
  LawyerFeeInput,
  LawyerFeeInterpretiveCases,
  LawyerFeeKlacModifier,
  LawyerFeeModifierChange,
  LawyerFeeModifiers,
  LawyerFeeNoOralHearingModifier,
  LawyerFeeNoOralHearingTrigger,
  LawyerFeeProvisionalModifier,
  LawyerFeeResult,
  LawyerFeeSourceLaw,
  LawyerFeeStackingPolicy,
  LitigationCostDistributionDirective,
  LitigationCostDistributionMode,
  LitigationCostDistributionParts,
  LitigationCostDistributionResult,
  LitigationCostInput,
  LitigationCostResult,
  NoOralHearingReason,
  StampDutyAppealsMultipliers,
  StampDutyBracket,
  StampDutyDataset,
  StampDutyElectronicFilingDiscount,
  StampDutyHistoryNote,
  StampDutyInput,
  StampDutyResult,
  StampDutyRoundingPolicy,
  StampDutySourceLaw,
  StampDutySpecialProcedureEntry,
  StampDutySpecialProcedures,
} from "./litigation-cost";
export {
  applyLawyerFeeDiscounts,
  appliedDomains,
  applyStampDutyRounding,
  CASE_TYPE_META,
  caseCode,
  caseNameKo,
  computeDeliveryFee,
  computeLitigationCost,
  computeLawyerFee,
  computeStampDuty,
  deliveryDatasetVersionTag,
  divideEqually,
  divideProportionally,
  getAppealsMultiplier,
  getDeliveryCount,
  getDeliveryUnitPriceAt,
  getLawyerFeeBracket,
  getStampDutyBracket,
  isCaseType,
  isCivilOrFamily,
  KLAC_DEFAULT_RATE,
  LAWYER_FEE_MULTIPLIER_MAX,
  LAWYER_FEE_MULTIPLIER_MIN,
  lawyerFeeDatasetVersionTag,
  lawyerFeeDiscountMultiplier,
  listCaseTypes,
  loadDeliveryDataset,
  loadLawyerFeeDataset,
  loadStampDutyDataset,
  stampDutyVersionTag,
  validateDeliveryFeeInput,
  validateDistributeEqualInput,
  validateDistributeProportionalInput,
  validateKlacDiscountScope,
  validateLawyerFeeInput,
  validateStampDutyInput,
} from "./litigation-cost";
